dist:
  name: ck-otelcol
  description: ck-otel-collector 
  output_path: ./cmd
  version: 0.1.0

receivers:
  - gomod: github.com/ck-otel-collector/receiver/otlpreceiver v0.0.0-00010101000000-000000000000

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.128.0
  - gomod: github.com/ck-otel-collector/processor/metricsaggregatorprocessor v0.0.0-00010101000000-000000000000

exporters:
  - gomod: github.com/ck-otel-collector/exporter/prometheusexporter v0.0.0-00010101000000-000000000000
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.128.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.128.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.128.0

replaces:
  - github.com/ck-otel-collector/receiver/otlpreceiver => ../receiver/otlpreceiver
  - github.com/ck-otel-collector/processor/metricsaggregatorprocessor => ../processor/metricsaggregatorprocessor
  - github.com/ck-otel-collector/exporter/prometheusexporter => ../exporter/prometheusexporter
  - github.com/ck-otel-collector/internal/common/testdata => ../internal/common/testdata
  - github.com/ck-otel-collector/internal/coreinternal/testutil => ../internal/coreinternal/testutil
  - github.com/ck-otel-collector/internal/sharedcomponent => ../internal/sharedcomponent
  - github.com/ck-otel-collector/internal/statusutil => ../internal/statusutil
  - github.com/ck-otel-collector/internal/telemetry => ../internal/telemetry